"""Phase 2B results page: results/phase2b_results.md, generated from results/phase2b/scores.json (written by the
registered src/phase2b.py `score`).  Not part of the registration: rendering only, plus `score_result`, which recomputes
the scores dict from the committed runs with the REGISTERED functions (so the ledger can check that scores.json
regenerates).  Nothing here computes a verdict of its own.

    python -m src.phase2b_report
"""

from __future__ import annotations

import json
from pathlib import Path

from . import phase2b as P

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
OUT = RESULTS / "phase2b"
RESULTS_MD = RESULTS / "phase2b_results.md"
NAMES = {"std": "1 (standard)", "out16": "2 (v ÷16, primary)", "out16b": "2b (v and b ÷16, secondary)",
         "glob": "3 (global ÷12.18)", "globcm": "3cm (global ÷16.14)"}
CRIT_ORDER = ("R_s", "R_l_rho2", "R_l_acc", "O", "N")
CRIT_NAME = {"R_s": "R_s", "R_l_rho2": "R_ℓ-ρ₂", "R_l_acc": "R_ℓ-acc", "O": "O", "N": "N"}
PT_NAME = {"scale_1.25s*": "s = 1.25 s*", "scale_2s*": "s = 2 s*", "scale_3s*": "s = 3 s*", "bce_0.1": "BCE = 0.1",
           "bce_0.03": "BCE = 0.03", "bce_0.01": "BCE = 0.01", "match_step": "arm 1's step to 3 s*",
           "end_T_C": "T_C = 40,000"}
Q_NAME = {"rho2": "ρ₂", "acc_shuffled": "shuffled", "acc_reversed": "reversed", "s": "s"}


def score_result():
    """The scores dict exactly as src/phase2b.py `score` assembles it (same registered functions, same order)."""
    runs = P._rows(OUT / "runs.jsonl")
    ST = P.score_tables(runs)
    return {**ST, "DESCRIPTIVE": P.descriptive(runs), "no_criterion_is_a_forecast": P.NO_CRITERION_IS_A_FORECAST}


def _f(v, d=3, sign=False):
    if v is None:
        return "—"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, int):
        return f"{v:,}"
    return f"{v:+.{d}f}" if sign else f"{v:.{d}f}"


def _iqr(q, d=3):
    if not q:
        return "—"
    return f"{_f(q['median'], d)} [{_f(q['q25'], d)}–{_f(q['q75'], d)}]"


def _cell(c):
    p, q = c.split("|")
    return f"{PT_NAME[p]}, {Q_NAME[q]}"


def _crit_stat(k, c):
    if k == "O":
        return (f"{c['n_above_s_star']}/{c['n_runs']} runs with s(t_on) > s* (≥ 75%); no lasting onset "
                f"{c['n_no_onset']}")
    if k == "N":
        worst = max(range(len(c["upper"])), key=lambda j: c["upper"][j] - c["delta"][j])
        return (f"every upper end < δ: {_f(c['all_upper_lt_delta'])}; closest cell ({_cell(c['cells'][worst])}): upper "
                f"{_f(c['upper'][worst], 4, True)} vs δ {c['delta'][worst]}; min reach {min(c['n_both'])}/80")
    j = min(range(len(c["lower"])), key=lambda i: c["lower"][i])
    return (f"every lower end > 0: {_f(c['all_lower_gt_0'])}; smallest ({_cell(c['cells'][j])}): lower "
            f"{_f(c['lower'][j], 4, True)}; min reach {min(c['n_both'])}/80")


def render_md(S):
    o = S["outcome"]
    L = ["# Phase 2B results: the lever (output learning rate) on the simplicity-bias benchmark", "",
         "Generated by `python -m src.phase2b_report` from `results/phase2b/scores.json` (registered `src/phase2b.py` "
         "`score`). Registration: `results/phase2b_registration.md` (commit 9239902; stamp 90c4e90; OpenTimestamps "
         "proof f62b4a5). 80 seeds (2,962,000–2,962,079) × 5 arms, 40,000 Adam steps each. No criterion is a "
         "forecast: every criterion compares observed outcomes after all 400 runs ended.", "",
         f"**Primary outcome (arm 2 with N for arms 3 and 3cm): {o['primary']}**", ""]
    L += [f"- {s}" for s in o["statements"]]
    s2 = o["secondary_arm_2b"]
    L += [f"- Secondary (arm 2b, its own verdict; never changes the primary): "
          + ", ".join(f"{CRIT_NAME[k]} {v}" for k, v in s2["verdicts"].items()) + ".",
          f"- Arm 2b's R_ℓ-acc was registered with an expected FAIL (power 0.18 from the exploration); observed: "
          f"{s2['verdicts']['R_l_acc']}.", ""]
    L += ["## Verdicts", "", "| arm | criterion | verdict | statistic |", "|---|---|---|---|"]
    for a in P.OUTPUT_ARMS + P.GLOBAL_ARMS:
        C = S["arms"][a]["criteria"]
        for k in CRIT_ORDER:
            if k in C:
                L.append(f"| {NAMES[a]} | {CRIT_NAME[k]} | {C[k]['verdict']} | {_crit_stat(k, C[k])} |")
    nf = S["nonfinite_runs"]
    L += ["", "## Validity", "",
          f"- Non-finite runs: {len(nf)}" + (" (" + ", ".join(f"{a} {s} at step {t}" for a, s, t in nf) + ")"
                                              if nf else "") + ". A non-finite run voids only the criteria that use "
          "its arm (arm 1: every criterion; D5).",
          "- Reach (≥ 72/80 seeds reaching every cell in both arms): " + "; ".join(
              f"{NAMES[a].split(' ')[0]} min {min(min(c['n_both']) for c in S['arms'][a]['criteria'].values() if 'n_both' in c)}/80"
              for a in P.OUTPUT_ARMS + P.GLOBAL_ARMS) + ".", ""]
    L += ["## Cells: median paired Δ (arm − arm 1) [95% bootstrap interval], seeds up/down", "",
          "| point | quantity | " + " | ".join(NAMES[a] for a in P.OUTPUT_ARMS + P.GLOBAL_ARMS) + " |",
          "|---|---|" + "---|" * 4]
    for c in P.CELLS:
        p, q = c.split("|")
        row = []
        for a in P.OUTPUT_ARMS + P.GLOBAL_ARMS:
            e = S["arms"][a]["cells"][c]
            row.append(f"{_f(e['median'], 3, True)} [{_f(e['lo'], 3, True)}, {_f(e['hi'], 3, True)}] "
                       f"{e['n_up']}/{e['n_down']}")
        L.append(f"| {PT_NAME[p]} | {Q_NAME[q]} | " + " | ".join(row) + " |")
    D = S["DESCRIPTIVE"]["arms"]
    L += ["", "## DESCRIPTIVE (registered as such; never a verdict)", "",
          "### End of training (T_C = 40,000): **no endpoint advantage is claimed**", "",
          "Median paired Δ vs arm 1 [IQR], seeds up/down; descriptive 95% bootstrap interval of the median.", "",
          "| arm | ρ₂ | shuffled | reversed | s | ρ₂ interval |", "|---|---|---|---|---|---|"]
    for a in P.ARMS[1:]:
        d = D[a]["paired_vs_arm1"]
        cells = [f"{_iqr(d[f'end_T_C|{q}'])} {d[f'end_T_C|{q}']['n_up']}/{d[f'end_T_C|{q}']['n_down']}"
                 for q in ("rho2", "acc_shuffled", "acc_reversed", "s")]
        b = D[a]["endpoint_bootstrap_DESCRIPTIVE"]["rho2"]
        L.append(f"| {NAMES[a]} | " + " | ".join(cells) + f" | [{_f(b['lo'], 3, True)}, {_f(b['hi'], 3, True)}] |")
    L += ["", "Values at T_C (median [IQR]): " + "; ".join(
        f"{NAMES[a].split(' ')[0]} ρ₂ {_iqr(D[a]['values']['end_T_C']['rho2'])}, s {_iqr(D[a]['values']['end_T_C']['s'], 2)}"
        for a in P.ARMS) + ".", "",
          "### The matched step (each arm at arm 1's step to 3 s*, vs arm 1 at 3 s*)", "",
          "| arm | Δρ₂ | Δshuffled | Δreversed | s at that step |", "|---|---|---|---|---|"]
    for a in P.ARMS[1:]:
        d = D[a]["paired_vs_arm1"]
        L.append(f"| {NAMES[a]} | " + " | ".join(
            f"{_iqr(d[f'match_step|{q}'])} {d[f'match_step|{q}']['n_up']}/{d[f'match_step|{q}']['n_down']}"
            for q in ("rho2", "acc_shuffled", "acc_reversed")) + f" | {_iqr(D[a]['values']['match_step']['s'], 2)} |")
    L += ["", "### Steps to each matched point (median [IQR]) and step cost (per-seed ratio to arm 1)", "",
          "| point | " + " | ".join(NAMES[a] for a in P.ARMS) + " |", "|---|" + "---|" * 5]
    for p in P.POINTS:
        row = [_iqr(D["std"]["steps_to"][p], 0)]
        for a in P.ARMS[1:]:
            row.append(f"{_iqr(D[a]['steps_to'][p], 0)} (×{_iqr(D[a]['steps_ratio_vs_arm1'][p], 2)})")
        L.append(f"| {PT_NAME[p]} | " + " | ".join(row) + " |")
    L += ["", "### Onset location (lasting to T_C; not tested against the fold)", "",
          "| arm | lasting onsets | s/s* median [IQR] | s/s_F median [IQR] | in [1, 1.25] s* | at or below s* | "
          "from init |", "|---|---|---|---|---|---|---|"]
    for a in P.ARMS:
        on = D[a]["onset"]
        L.append(f"| {NAMES[a]} | {on['n_lasting']}/80 | {_iqr(on['s_over_s_star'], 2)} | {_iqr(on['s_over_s_F'], 2)} "
                 f"| {on['n_in_[1,1.25]s*']} | {on['n_below_or_at_s*']} | {on['n_from_init']} |")
    L += ["", "### Two-sided equivalence for the global arms (95% interval inside (−δ, δ))", ""]
    for a in P.GLOBAL_ARMS:
        eq = D[a]["two_sided_equivalence"]
        out = [f"{_cell(c)} [{_f(e['lo'], 3, True)}, {_f(e['hi'], 3, True)}]" for c, e in eq.items() if not e["within"]]
        L.append(f"- {NAMES[a]}: {sum(e['within'] for e in eq.values())}/18 cells within"
                 + (("; outside: " + "; ".join(out)) if out else "") + ".")
    L += ["", "Maximum relative overshoot at the matched scales: " + ", ".join(
        f"{NAMES[a].split(' ')[0]} {_f(D[a]['max_overshoot_scale'], 4)}" for a in P.ARMS) + "."]
    return "\n".join(L) + "\n"


def main():
    S = json.loads((OUT / "scores.json").read_text())
    RESULTS_MD.write_text(render_md(S))
    print(RESULTS_MD.read_text())


if __name__ == "__main__":
    main()
