"""Phase 3 results page (results/phase3_results.md), generated whole from results/phase3/scores.json and frozen.json.
The ledger (verify_ledger.phase3_checks) asserts that scores.json regenerates from the committed rows with the
registered scoring code and that this page regenerates from it.

    python -m src.phase3_report
"""

from __future__ import annotations

import json

from . import phase3_w4 as P

RESULTS_MD = P.RESULTS / "phase3_results.md"


def score_result():
    """The scores dict exactly as phase3_w4.score assembles it (the registered functions, unchanged)."""
    fr = json.loads((P.OUT / "frozen.json").read_text())
    res = {"label": "PHASE 3 (registered)", "forecasts_sha256": P._sha(P.OUT / "forecasts.sha256"),
           "registration_sha256_file_sha256": P._sha(P.OUT / "registration.sha256"),
           "collapse_random_holds_T4": fr["collapse_random_holds_T4"], "arms": {}}
    for arm in P.ARMS:
        _, rows = P._frozen_by_seed(arm)
        R = P.table(arm, rows, P._rows(P._runs_file(arm)), P._rows(P._obs_file(arm)))
        res["arms"][arm] = P.score_arm(arm, R, fr["pilot_median_chi_tsw"][arm], fr["tau"][arm]["tau_cross"],
                                       fr["tau"][arm]["tau_lag"])
    return res


def _f(v, d=3):
    if v is None:
        return "—"
    if isinstance(v, float):
        return f"{v:.{d}f}"
    return str(v)


def render_md(S):
    fr = json.loads((P.OUT / "frozen.json").read_text())
    c = S["collapse_random_holds_T4"]
    L = ["# Phase 3 results: the lag law at width 4 on the asymmetric windows", "",
         "Registered: `results/phase3_registration.md` (registration 7a9d791, stamp 2bcbda1, OpenTimestamps 16a46bb).",
         "Generated by `src/phase3_report.py` from `results/phase3/scores.json` (the ledger checks both regenerate).", "",
         "## The finding reported first: random holds collapse (T4's 710 registered random holds; descriptive)", "",
         f"- **Genuine four-unit (1111) unplaced landings: {c['n_genuine_four_unit_unplaced']} of {c['n_random_holds']}.** "
         f"On the seed's own Q point: {c['n_on_Q_own_point']}; own S point: {c['n_on_S_own_point']}.",
         f"- Newton accepted: {c['n_newton_accepted']}; every one a coinciding-unit point "
         f"({c['n_coinciding_unit_points']}; {c['n_placed']} placed). On T4: {c['n_on_T4']}.", "",
         "| landing type | holds |", "|---|---|"]
    L += [f"| {k} | {v} |" for k, v in c["by_type"].items()]
    L += ["", "So Q and S are MECHANISM tests from a branch point: they ask whether a branch's signed lag is forecast once",
          "a run is on it, not whether training reaches it.", "", "## Verdicts", "",
          "| arm | role | gate | valid | C1 | C2 | C3 | C4 | S | outcome |", "|---|---|---|---|---|---|---|---|---|---|"]
    for a in P.ARMS:
        r = S["arms"][a]
        g = r["gate"]
        v = lambda k: r[k]["verdict"] if k in r else "—"                     # noqa: E731
        L.append(f"| {a} | {P.ROLE[a]} | {g['n_on_copy']}/{g['n_runs']} on copy, hold G>0 {g['n_hold_G_positive']} "
                 f"({'PASS' if g['pass'] else 'FAIL'}) | {r.get('valid')} | {v('C1')} | {v('C2')} | {v('C3')} | "
                 f"{v('C4')} | {v('S')} | **{r['outcome']}** |")
    rp = P.OUT / "repro_check.json"
    rc = json.loads(rp.read_text()) if rp.exists() else None
    L += ["", "## Run continuity (the author's requested facts)", "",
          "- The Q `run` stalled at 14:36 (2026-10-06) with 13 per-seed rows written. It was restarted at 15:28:59 with the",
          "  registered command, which **RESUMED FROM SAVED PER-SEED RESULTS**: the 13 pre-stall rows were kept; seed",
          "  7,430,013 (in progress at the stall, no row) was retrained from scratch; there is no in-seed checkpoint.",
          "- Forecasts were committed (1ca653a) before any observation.",
          ("- **The pre-stall seeds REPRODUCE IDENTICALLY:** " if rc and rc["all_identical"] else
           "- Reproducibility check: ") + (", ".join(f"{k} {'identical' if v['identical'] else 'DIFFERS'}"
                                                     for k, v in rc["seeds"].items()) if rc else "not run") +
          " (POST HOC, `src/phase3_repro_check.py` → `results/phase3/repro_check.json`; registered `run_one` recomputed vs",
          "  the committed rows, timing fields excluded)."]
    q4 = S["arms"]["Q"].get("C4", {})
    qci = q4.get("ci95") or [None, None]
    L += ["", f"**Q's C4 (verdict {q4.get('verdict')}, 95% interval [{_f(qci[0], 1)}, {_f(qci[1], 1)}]) was a KNOWN RISK "
          "recorded in the registration before any registered run** (pilot C4 interval [−74.9, +29.0]; pilot crossing",
          "errors all late, 18–101 steps; lag errors ≤ 4). C4 was registered unchanged.", ""]
    for a in P.ARMS:
        r = S["arms"][a]
        L += [f"## Arm {a}", ""]
        if r["outcome"] == "UNRESOLVED (gate)":
            L += ["Gate failed; nothing scored.", ""]
            continue
        fa = fr["arms"][a]
        L += [f"- Seeds {r['n_runs']}; on copy at release {r['n_on_copy']}; trained (eligible) {r['n_eligible']}; "
              f"counted, not trained: {fa['not_trained_reasons']}; over cap {r['n_over_cap_not_trained']}; "
              f"aborted (RSS) {r['n_aborted_rss']}.",
              f"- Base (crossing) runs {r['n_base_crossing_runs']}; scored {r['n_scored']} "
              f"(with forecast {r['n_scored_with_forecast']}, misses {r['n_scored_miss']}); not following "
              f"{r['n_on_copy_not_following']}; cutoff not before the crossing {r['n_crossed_cutoff_not_before']}; "
              f"NaN recomputations differing {r['n_nan_recompute_differs']} of {r['n_nan_recompute_checked']}.",
              f"- τ_cross {r['tau_cross']}, τ_lag {r['tau_lag']}.", "",
              "| criterion | statistic | verdict |", "|---|---|---|"]
        for k in ("C1", "C2"):
            L.append(f"| {k} | within {r[k].get('n_within')}/{r[k].get('n')} = {_f(r[k].get('frac_within'))} | "
                     f"{r[k]['verdict']} |")
        L.append(f"| C3 | median r_obs/r_fc {_f(r['C3'].get('median_ratio'), 4)} (n {r['C3'].get('n')}, |lag_fc| ≥ 6) | "
                 f"{r['C3']['verdict']} |")
        ci = r["C4"].get("ci95") or [None, None]
        L.append(f"| C4 | mean D {_f(r['C4'].get('mean_D'), 2)}, 95% [{_f(ci[0], 2)}, {_f(ci[1], 2)}] (n {r['C4'].get('n')}) | "
                 f"{r['C4']['verdict']} |")
        if "S" in r:
            L.append(f"| S | both negative {r['S'].get('n_both_negative')}/{r['S'].get('n_eligible')} = "
                     f"{_f(r['S'].get('frac'))} | {r['S']['verdict']} |")
        L += ["", "Validity: " + ", ".join(f"{k} {'ok' if v else 'FAIL'}" for k, v in r["validity"].items()) + ".",
              "Inputs: " + ", ".join(f"{k} {_f(v, 4) if isinstance(v, float) else v}"
                                     for k, v in r["validity_inputs"].items()) + ".", ""]
        d = r.get("DESCRIPTIVE", {})
        if "S_descriptive" in d:
            s_ = d["S_descriptive"]
            L.append(f"- DESCRIPTIVE S on {a}: both negative {s_['n_both_negative']}/{s_['n_eligible']} "
                     f"({_f(s_['frac'])}).")
        Ld = d.get("L1_L5_on_r_fc", {})
        L.append("- DESCRIPTIVE L1–L5 on r_fc: " + ", ".join(
            f"{k} {_f(v, 4) if isinstance(v, float) else ([round(t, 4) for t in v] if isinstance(v, list) else v)}"
            for k, v in Ld.items()) + ".")
        if d.get("horizon_steps_t_obs_minus_t_c"):
            L.append(f"- Horizon t_obs − t_c (min, median, max): {d['horizon_steps_t_obs_minus_t_c']}.")
        if "sensitivity_excluding_hold_G_positive" in d:
            L.append(f"- DESCRIPTIVE sensitivity without the runs with G > 0 in the hold: "
                     f"{d['sensitivity_excluding_hold_G_positive']}.")
        L.append("")
    return "\n".join(L) + "\n"


def main():
    S = json.loads((P.OUT / "scores.json").read_text())
    RESULTS_MD.write_text(render_md(S))
    print(RESULTS_MD.read_text())


if __name__ == "__main__":
    main()
