"""Phase 1C results page: results/phase1c_results.md, generated from results/phase1c/scores.json (written by the
registered src/phase1c.py `score`).  Not part of the registration (rendering only; no number is computed here that is
not in scores.json, except counts read from the committed runs files).

    python -m src.phase1c_report
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
OUT = RESULTS / "phase1c"
RESULTS_MD = RESULTS / "phase1c_results.md"
LABEL = {"W1": "W1", "G": "G", "T": "T", "Tp": "T′"}


def _f(v, d=3):
    if v is None:
        return "—"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return f"{v:.{d}f}"
    return str(v)


def _crit_cell(c):
    if not c or "verdict" not in c:
        return "—"
    v = c["verdict"]
    if "n_within" in c:
        return f"{v} ({c['n_within']}/{c['n']}, misses {c['n_miss']})"
    if "median_ratio" in c:
        return f"{v} (median {_f(c['median_ratio'])}, n {c['n']})"
    if "ci95" in c:
        lo, hi = c["ci95"]
        return f"{v} ([{_f(lo, 1)}, {_f(hi, 1)}], n {c['n']})"
    if "n_both_negative" in c:
        return f"{v} ({c['n_both_negative']}/{c['n_eligible']}, misses {c.get('n_eligible_miss', 0)})"
    return v


def _hz(h):
    if not h or not h.get("n"):
        return "—"
    return f"{_f(h['min'], 0)} / {_f(h['median'], 0)} / {_f(h['max'], 0)}"


def _hzl(h):
    if not h or not h.get("n"):
        return "—"
    return f"{_f(h['min'], 2)} / {_f(h['median'], 2)} / {_f(h['max'], 2)}"


def run_counts(arm):
    rows = [json.loads(ln) for ln in (OUT / f"runs_{arm}.jsonl").read_text().splitlines()]
    st = {}
    for r in rows:
        st[r.get("status", "?")] = st.get(r.get("status", "?"), 0) + 1
    return {"n_runs": len(rows), "n_eligible": sum(1 for r in rows if r.get("eligible") and r.get("status") == "ok"),
            "statuses": st}


def render_md(S):
    A = S["arms"]
    g = S["phase2_gate"]
    L = ["# Phase 1C results: the registered causal replication on fresh seeds", "",
         "**REGISTERED TEST, SCORED.** Registration: `results/phase1c_registration.md`, commit 6433edc. Its OpenTimestamps "
         "proof was committed as f458c4c. The forecasts were committed before any observation (`forecasts.sha256`). "
         "Every number below comes from `results/phase1c/scores.json` (`phase1c.score`). This page is generated by "
         "`src/phase1c_report.py`.", "",
         f"**Gate to Phase 2 (W1 PASS and (G or T PASS)): {'PASS' if g['pass'] else 'FAIL'}.** "
         f"W1 {A['W1']['outcome']}; G {A['G']['outcome']}; T {A['T']['outcome']}; T′ {A['Tp']['outcome']} "
         "(own verdict).", "",
         "## 1. Verdicts (registered: C1–C4, + S for T′)", "",
         "| arm | f | outcome | C1 \\|t_fc − t_obs\\| ≤ τ_cross | C2 \\|lag_fc − lag_obs\\| ≤ τ_lag | C3 median r_obs/r_fc ∈ [1 ± b] | "
         "C4 bootstrap interval of mean D (PASS iff upper < 0) | S |",
         "|---|---|---|---|---|---|---|---|"]
    for a in ("W1", "G", "T", "Tp"):
        o = A[a]
        L.append(f"| {LABEL[a]} | {o['f']} | **{o['outcome']}** | {_crit_cell(o.get('C1'))} | {_crit_cell(o.get('C2'))} | "
                 f"{_crit_cell(o.get('C3'))} | {_crit_cell(o.get('C4'))} | {_crit_cell(o.get('S')) if a == 'Tp' else '—'} |")
    L += ["", "τ_cross / τ_lag / b: W1 10 / 15 / 0.20; G 10 / 10 / 0.15; T 15 / 5 / 0.10; T′ 30 / 5 / 0.10.", "",
          "## 2. Gate, validity and counts", "",
          "| arm | runs | eligible (scored copy) | gate | crossing runs (base) | cutoff before crossing | scored | misses | "
          "NaN recomputation differs | validity |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for a in ("W1", "G", "T", "Tp"):
        o = A[a]
        rc = run_counts(a)
        gt = o.get("gate", {})
        gate = "none (no hold)" if not gt.get("applies", True) else ("PASS" if gt.get("pass") else "FAIL") + \
            (f" ({gt.get('n_on_branch')}/{gt.get('n_runs')} on branch, hold G > 0: {gt.get('n_hold_G_positive')})"
             if "n_on_branch" in gt else "")
        cv = o.get("cutoff_validity", {})
        failed = [k for k, v in (o.get("validity") or {}).items() if not v]
        val = "valid" if o.get("valid") else ("not valid: " + ", ".join(failed) if failed else "not valid (gate)")
        L.append(f"| {LABEL[a]} | {rc['n_runs']} | {rc['n_eligible']} | {gate} | {_f(o.get('n_base_crossing_runs'))} | "
                 f"{_f(cv.get('n_cutoff_before_crossing'))}/{_f(cv.get('n_crossing_runs'))} | {_f(o.get('n_scored'))} | "
                 f"{_f(o.get('n_scored_miss'))} | {_f(o.get('n_nan_recompute_differs'))}/{_f(o.get('n_nan_recompute_checked'))} | "
                 f"{val} |")
    L += ["", "Validity conditions per arm (registered; W1: Track A's counts; G, T, T′: the registered V1–V7 over the 1C "
          "scored set; every arm: the 90% cutoff rule and the NaN recomputation):", ""]
    for a in ("W1", "G", "T", "Tp"):
        v = A[a].get("validity") or {}
        L.append(f"- {LABEL[a]}: " + (", ".join(f"{k} {'ok' if x else 'FAILS'}" for k, x in v.items()) or "—"))
    L += ["", "## 3. Descriptive (not verdicts)", "",
          "**Horizons** (scored runs; min / median / max). Steps from the cutoff to the crossing and to the actual "
          "switch, and the same in lags (÷ max(|lag_obs|, 1)).", "",
          "| arm | t_obs − t_c (steps) | t_sw − t_c (steps) | t_obs − t_c (lags) | t_sw − t_c (lags) |",
          "|---|---|---|---|---|"]
    for a in ("W1", "G", "T", "Tp"):
        h = (A[a].get("DESCRIPTIVE") or {}).get("horizon") or {}
        L.append(f"| {LABEL[a]} | {_hz(h.get('cross_steps'))} | {_hz(h.get('switch_steps'))} | {_hzl(h.get('cross_lags'))} | "
                 f"{_hzl(h.get('switch_lags'))} |")
    L += ["", "**Errors at the other f** (the criteria statistics, descriptive; base runs whose other-f cutoff is "
          "before the crossing).", "",
          "| arm | other f | runs | C1 | C2 | C3 | C4 | S |", "|---|---|---|---|---|---|---|---|"]
    for a in ("W1", "G", "T", "Tp"):
        d = (A[a].get("DESCRIPTIVE") or {}).get("other_f")
        if not d:
            L.append(f"| {LABEL[a]} | — | — | — | — | — | — | — |")
            continue
        c = d["criteria_stats"]
        L.append(f"| {LABEL[a]} | {d['f']} | {d['n_cutoff_before_crossing']} | {_crit_cell(c.get('C1'))} | "
                 f"{_crit_cell(c.get('C2'))} | {_crit_cell(c.get('C3'))} | {_crit_cell(c.get('C4'))} | "
                 f"{_crit_cell(c.get('S')) if a == 'Tp' else '—'} |")
    L += ["", "**Forecast closer than the no-lag forecast** (the draft's C4; descriptive): " + "; ".join(
        f"{LABEL[a]} {A[a]['C4'].get('DESCRIPTIVE_n_forecast_closer', '—')}/{A[a]['C4'].get('n', '—')}"
        for a in ("W1", "G", "T", "Tp") if "C4" in A[a]) + ".", "",
          "**L1–L5 with r_fc in place of the registered prediction** (descriptive; the registered functions; W1 Track "
          "A's L1–L3; L2 is the registered closed form, not a 1C forecast).", "",
          "| arm | L1 median r_obs/r_fc | L2 median r_obs/r_cf | L3 Spearman | L4 | L5 |", "|---|---|---|---|---|---|"]
    for a in ("W1", "G", "T", "Tp"):
        d = (A[a].get("DESCRIPTIVE") or {}).get("L1_L5_on_r_fc") or {}

        def cell(k, key):
            x = d.get(k) or {}
            if key == "ci95":
                ci = x.get("ci95")
                return f"{x.get('verdict', '—')} [{_f(ci[0], 4)}, {_f(ci[1], 4)}]" if ci else "—"
            return f"{x.get('verdict', '—')} ({_f(x.get(key))})" if x else "—"
        L.append(f"| {LABEL[a]} | {cell('L1', 'median_ratio')} | {cell('L2', 'median_ratio')} | {cell('L3', 'spearman')} | "
                 f"{cell('L4', 'ci95')} | {cell('L5', 'ci95')} |")
    for a in ("G", "T"):
        s = (A[a].get("DESCRIPTIVE") or {}).get("sensitivity_excluding_hold_G_positive")
        if s:
            L.append("")
            L.append(f"Sensitivity, {LABEL[a]} without runs with G > 0 in the hold (descriptive): n = {s['n_scored']}; " +
                     ", ".join(f"{k} {v}" for k, v in s.items() if k != "n_scored") + ".")
    L += ["", "Notes: horizons in lags are large where |lag_obs| is a few steps (÷ max(|lag_obs|, 1)). The W1 L1 band "
          "[0.90, 1.10] is Track A's; the registered W1 criterion is C3 with b = 0.20, set from the est-seed bias "
          "(median 1.172; registration §8).", "", "## 4. Reproduce", "", "```",
          "python -m src.phase1c run W1|G|T|Tp; python -m src.phase1c finalize   # committed before observe",
          "python -m src.phase1c observe W1|G|T|Tp; python -m src.phase1c score; python -m src.phase1c_report",
          "```", ""]
    return "\n".join(L)


def score_result():
    """The registered `phase1c.score` computation, in memory (no write): the same functions, the same inputs.  The
    ledger compares it with the committed scores.json."""
    from . import gelu_transfer as G
    from . import phase1c as P
    from . import width2_asym as W
    res = {"label": "PHASE 1C (registered causal replication)", "forecasts_sha256": P._sha(P.OUT / "forecasts.sha256"),
           "registration_sha256_file_sha256": P._sha(P.OUT / "registration.sha256"), "arms": {}}
    for arm in P.ARMS:
        R = P.table(arm, P._rows(P._runs_file(arm)), P._rows(P._obs_file(arm)))
        if arm == "W1":
            pc, sp = None, None
        elif arm == "G":
            pc = json.loads((G.OUT / "pilot.json").read_text())["pilot_median_chi_tsw"][G.PRIMARY]
            sp = G._land()["s_glob"]
        else:
            pc = json.loads((W.OUT / "pilot.json").read_text())["arms"][P.w2a_arm(arm)]["pilot_median_chi_tsw"]
            sp = R["s_pop"]
        res["arms"][arm] = P.score_arm_1c(arm, R, pilot_chi=pc, s_pop=sp)
    res["phase2_gate"] = P.phase2_gate(res["arms"])
    return res


def main():
    S = json.loads((OUT / "scores.json").read_text())
    RESULTS_MD.write_text(render_md(S))
    print(RESULTS_MD)


if __name__ == "__main__":
    main()
