"""Phase 2A-PS2 results page (results/phase2a_ps2_results.md) from results/phase2a_ps2/scores.json.

score_result() rebuilds the scores dict exactly as the registered src/phase2a_ps2.py `score` assembles it (the same
registered functions, in the same order) from the committed frozen.json, frozen_parts.jsonl, runs.jsonl and
observed.jsonl; the ledger (phase2a_ps2_checks) asserts it equals the committed scores.json and that this page
regenerates from it.  The formatting helpers and the misses list are 2A-PS's report's (phase2a_ps_report).

    python -m src.phase2a_ps2_report
"""

from __future__ import annotations

import json

from . import phase2a_ps as PS
from . import phase2a_ps2 as P
from . import phase2a_ps_report as PSR

OUT = P.OUT
RESULTS_MD = P.RESULTS / "phase2a_ps2_results.md"

# The run/observe timeline and the machine figures, from results/phase2a_ps2/run.log and observe.log (`/usr/bin/time
# -l` of the coordinator's detached jobs; the logs themselves are not committed).
TIMELINE = {"registration": "a1bd625 (stamp 3a6f57b; OpenTimestamps proof b2564fa, committed and pushed BEFORE "
                            "training)",
            "run": ("2026-10-07 20:44:24", "2026-10-07 22:37:31", "exit 0"),
            "forecasts": "678f43d (committed and pushed BEFORE observation)",
            "observe": ("2026-10-07 22:49:24", "2026-10-08 18:20:34", "exit 0"),
            "run_max_rss_bytes": 992_690_176, "run_peak_footprint_bytes": 1_189_103_152,
            "observe_max_rss_bytes": 295_256_064, "observe_peak_footprint_bytes": 298_157_016}


def score_result():
    """The scores dict exactly as phase2a_ps2.score assembles it."""
    fr, rows = P._frozen()
    runs = P._rows(OUT / "runs.jsonl")
    obs = {(o["seed"], o["log2rho"]): o for o in P._rows(OUT / "observed.jsonl")}
    T = [P.run_row(P.seed_record(rows, r["seed"]), r, obs.get((r["seed"], r["log2rho"]), {})) for r in runs]
    ST = P.score_tables(T, fr["gate"]["pass"])
    return {"counts_PROMINENT": fr["counts"], "gate": fr["gate"], "over_cap_check": fr["over_cap_check"],
            "outcome": ST["outcome"], "verdicts": ST["verdicts"], "secondary_verdicts": ST.get("secondary_verdicts"),
            "criteria": ST["criteria"], "secondary": ST.get("secondary"), "validity": ST["validity"],
            "n_aborted_not_scored": ST["n_aborted_not_scored"], "aborted_runs": ST["aborted_runs"],
            "seed_exponents": ST.get("seed_exponents"), "rows": T, "DESCRIPTIVE": PS.descriptive(T),
            "DESCRIPTIVE_wide_crossing_rates": P.wide_crossing_rates(T),
            "DESCRIPTIVE_split_by_mc_agreement": PS.descriptive_split([r for r in T if not r.get("aborted")])
            if fr["gate"]["pass"] else None}


_f, _ci = PSR._f, PSR._ci


def _gb(b):
    return f"{b / 1e9:.2f} GB"


def render_md(S):
    c, g, oc = S["counts_PROMINENT"], S["gate"], S["over_cap_check"]
    bs, cbs = c["by_status"], c["class_by_status"]
    n = c["n_seeds"]
    fr = json.loads((OUT / "frozen.json").read_text())

    def cls(k):
        d = cbs[k]
        return f"clean {d['clean']}, none {d['none']}, mixed {d['mixed']}"
    act = fr["activity"]["inactive_unit_seeds"]
    L = ["# Phase 2A-PS2 results: the per-seed fold test, with the pipeline repaired", "",
         "**Registered after 2A-PS's UNRESOLVED (validity) outcome; 2A-PS's verdict stays.** This is a new "
         "registration, not a re-scoring of 2A-PS.", "",
         "Generated by `python -m src.phase2a_ps2_report` from `results/phase2a_ps2/scores.json` (registered "
         "`src/phase2a_ps2.py` `score`). Registration: `results/phase2a_ps2_registration.md` "
         f"({TIMELINE['registration']}). Forecasts: {TIMELINE['forecasts']}.", "",
         f"**Outcome: {S['outcome']}** (F, H, E_seed, C3, C4, P; C1 and C2 secondary: "
         f"C1 {S['secondary_verdicts']['C1']}, C2 {S['secondary_verdicts']['C2']}).", "",
         "## Freeze counts (all 600 registered seeds; read these first)", "",
         f"- **Untraceable: {c['n_untraceable']} of {n} ({100 * c['n_untraceable'] / n:.1f}%)**: M homotopy failed "
         f"{bs['untraceable: M homotopy failed']}, no upper fold {bs['untraceable: no upper fold']}, ρ₂ ≥ q on the "
         f"stable part {bs['untraceable: rho2 >= q on the stable part']}, homotopy point not stable "
         f"{bs['untraceable: homotopy point not stable']}, stable part not reaching the fold "
         f"{bs['untraceable: stable part does not reach the upper fold']}.",
         f"- s_F not validated {bs['s_F not validated']} ({cls('s_F not validated')}); Λ_F not validated "
         f"{bs['Lambda_F not validated']}; **no s\\* {bs['no s*']}** ({cls('no s*')}); release Newton failed "
         f"{bs['release Newton failed']} ({cls('release Newton failed')}).",
         f"- **Inactive unit at release: {bs[P.INACTIVE]}** ({cls(P.INACTIVE)}): "
         + ", ".join(f"{s:,} ({k}; share {sh:.1e})" for s, k, sh in act)
         + f". The smallest live share among scoreable releases is "
           f"{_f(fr['activity']['smallest_live_share_scoreable'])}.",
         f"- **Ineligible {bs['ineligible']}** ({cls('ineligible')}); t\\* not computable {bs[P.TSTAR_FAILED]}; "
         f"stall {bs[P.STALL]}; **over cap {bs[P.OVER_CAP]}** ({cls(P.OVER_CAP)}: "
         + ", ".join(f"{s:,}" for k in ("clean", "none", "mixed") for s in oc["seeds"][k]) + ").",
         f"- **Scoreable {c['n_scoreable']}: clean {c['scoreable_by_class']['clean']}, none "
         f"{c['scoreable_by_class']['none']}, mixed {c['scoreable_by_class']['mixed']}.**",
         f"- **Gate:** {g['n_clean_scoreable']} clean scoreable ≥ {g['min']}: {'PASS' if g['pass'] else 'FAIL'}. "
         f"**The author's over-cap check:** clean {oc['n_over_cap']['clean']}, none {oc['n_over_cap']['none']} "
         f"(≤ {oc['max_allowed']} each): {'PASS' if oc['pass'] else 'FAIL'}.",
         f"- Trained (caps 40/30/20 in seed order; {len(S['rows'])} runs): clean {fr['plan_counts']['clean']} "
         f"(2⁻¹⁴ and 2⁻¹⁶), none {fr['plan_counts']['none']}, mixed {fr['plan_counts']['mixed']} (2⁻¹⁴). "
         "**Counted, not trained** (scoreable beyond the caps): "
         + ", ".join(f"{k} {len(v)}" for k, v in fr["surplus_counted_not_trained"].items()) + ".",
         f"- Aborted runs (per-run 1 GB RSS cap; counted, not scored): {S['n_aborted_not_scored']}.", "",
         "## Verdicts (clean seeds at 2⁻¹⁶ unless stated; 10,000 seed resamples)", "",
         "| criterion | verdict | statistic |", "|---|---|---|"]
    for k in PS.PRIMARY:
        note = ""
        if k == "H":
            note = (" (none seeds, 2⁻¹⁴; re-tests 2A-PS's registered 30-minimum class rule, which measures whether "
                    "slab basins lie near the fold)")
        if k == "C3":
            note = " (registered KNOWN RISK: 2A-PS had 32/36 = 0.89)"
        L.append(f"| {k}{note} | **{S['verdicts'][k]}** | {PSR.crit_line(k, S['criteria'][k])} |")
    for k in PS.SECONDARY:
        L.append(f"| {k} (secondary; registered expected FAIL) | {S['secondary_verdicts'][k]} | "
                 f"{PSR.crit_line(k, S['secondary'][k])} |")
    v = S["validity"]
    L += ["", f"**Validity: {'OK' if v['ok'] else 'NOT OK'}.** Follow check on the seed's own M at 0.8·s_F "
          f"{_f(v['follow_frac'])} (needs ≥ 0.90); t_c < t_obs {_f(v['cutoff_before_frac'])} (needs ≥ 0.90; "
          f"not before: {v['n_cutoff_not_before']}); idle unit exactly 0 at every clean run "
          f"{_f(v['idle_zero_all'])}; signs fixed {_f(v['signs_fixed_all'])} ({v['n_runs_idle_sign']} clean runs).",
          f"F's falsifier (a crossing below s_F and at or below 1.25·s\\*): "
          f"{'FIRED' if S['criteria']['F']['falsified'] else 'did not fire'}.", "",
          "## DESCRIPTIVE ONLY: crossing by 1.25·s_F by wider-search class (never a criterion)", "",
          "The posthoc wider search (360 minima per seed at 1.01/1.02/1.05/1.10·s_F × ×1/×2/×4 × 30), frozen before "
          "the registration.", "",
          "| registered class, log₂ρ | wider-search class | runs | crossed | reached 1.25·s_F without crossing | "
          "crossing rate |", "|---|---|---|---|---|---|"]
    for key, b in S["DESCRIPTIVE_wide_crossing_rates"]["by"].items():
        k, l2, w = key.split(" ")
        L.append(f"| {k}, {l2} | {w.removeprefix('wide-')} | {b['n']} | {b['n_crossed']} | "
                 f"{b['n_reached_1.25_no_crossing']} | {_f(b['crossing_rate'])} |")
    L += ["", "## Misses by reason (every trained run; from the scored rows)", ""] + PSR.misses(S)
    L += ["", "## DESCRIPTIVE: split by the |m′c′| two-window agreement check (not a criterion)", "",
          "| subset | clean seeds | none seeds | F | H | E_seed | C3 | C4 | P | C1 | C2 | validity |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    D = S["DESCRIPTIVE_split_by_mc_agreement"]
    for tag in ("agree", "disagree"):
        d = D[tag]
        vv, sv = d["verdicts_DESCRIPTIVE"], d["secondary_verdicts_DESCRIPTIVE"]
        L.append(f"| {tag} | {d['n_clean_scored']} | {d['n_none']} | "
                 + " | ".join(vv[k] for k in PS.PRIMARY) + " | " + " | ".join(sv[k] for k in PS.SECONDARY)
                 + f" | {'OK' if d['validity_DESCRIPTIVE']['ok'] else 'NOT OK'} |")
    ph = PSR.posthoc_summary(S)
    L += ["", "## POST HOC (descriptive): 2A's fitted correction as a forecast", "",
          f"r = A ε^{{2/3}} + C ε ln(1/ε), A = {_f(S['DESCRIPTIVE']['posthoc_A'], 4)}, "
          f"C = {_f(S['DESCRIPTIVE']['posthoc_C'], 4)} (fitted on 2A's results), with each seed's ε̂_F. Clean seeds "
          f"at 2⁻¹⁶ (n {ph['n']}): r_obs/r_posthoc median {_f(ph['ratio_median'])}, > 1 at "
          f"{_f(ph['frac_ratio_gt_1'])}; mean |ln ŝ_c/s_obs| {_f(ph['mean_abs_log_err_posthoc'], 5)} (POST HOC) vs "
          f"{_f(ph['mean_abs_log_err_leading'], 5)} (registered leading order). Never a verdict.", "",
          "## DESCRIPTIVE: every trained cell", "",
          "| class, log₂ρ | runs | crossed | in [s_F, 1.25·s_F] | falsifier flag |", "|---|---|---|---|---|"]
    for k, b in sorted(S["DESCRIPTIVE"]["by_class_rate"].items()):
        L.append(f"| {k} | {b['n']} | {b['n_crossed']} | {b['n_in_F_window']} | {b['n_falsifier_flag']} |")
    t = TIMELINE
    L += ["", "## Timeline and machine", "",
          f"- `run`: {t['run'][0]} → {t['run'][1]}, {t['run'][2]}; 130/130 runs, every forecast ok.",
          f"- `observe`: {t['observe'][0]} → {t['observe'][1]}, {t['observe'][2]}; 130 rows.",
          f"- **Peak memory footprint of the `run` process {_gb(t['run_peak_footprint_bytes'])}** (maximum resident "
          f"set {_gb(t['run_max_rss_bytes'])}). This is the whole process over 130 runs. The registered per-run cap "
          f"(current RSS > 1 GiB, checked every 20,000 steps) was never hit: no run aborted. `observe`: footprint "
          f"{_gb(t['observe_peak_footprint_bytes'])}.",
          "- One process, nice 15, one thread; memory gate before each job and between runs.", "",
          "Mixed seeds enter no criterion. Design: `results/designs/phase2a_ps2_design.md`.", ""]
    return "\n".join(L)


def main():
    S = json.loads((OUT / "scores.json").read_text())
    RESULTS_MD.write_text(render_md(S))
    print(RESULTS_MD.read_text())


if __name__ == "__main__":
    main()
