"""Phase 2A results page: results/phase2a_results.md, generated from results/phase2a/scores.json (written by the
registered src/phase2a.py `score`).  Not part of the registration: rendering only, plus `score_result`, which recomputes
the scores dict from the committed rows with the REGISTERED functions (so the ledger can check that scores.json
regenerates).  Nothing here computes a verdict of its own.

    python -m src.phase2a_report
"""

from __future__ import annotations

import json
from pathlib import Path

from . import causal_forecast_fold as CFF
from . import phase2a as P

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
OUT = RESULTS / "phase2a"
RESULTS_MD = RESULTS / "phase2a_results.md"


def score_result():
    """The scores dict exactly as src/phase2a.py `score` assembles it (same registered functions, same order)."""
    fr = P._frozen(); Pj = P._pilot()
    holds = P._rows(OUT / "holds.jsonl")
    g = P.gate([h["label"] for h in holds])
    runs = P._rows(OUT / "runs.jsonl"); obs = P._rows(OUT / "observed.jsonl")
    T = P.rate_table(fr, runs, obs) if g["pass"] else []
    ST = P.score_tables(T, fr["s_F"], fr["s_star"], Pj["tau1"], Pj["tau2"], g["pass"])
    tight_T = [{**r, "t_c": (r["tight"] or {}).get("t_c"), "has_fc": CFF.has_forecast(r["tight"]),
                **{k: (r["tight"] or {}).get(k) for k in ("t_fc", "t_F_fc", "delay_fc", "eps_fc", "r_fc")}} for r in T]
    return {"gate": g, "validity": ST["validity"], "criteria": ST["criteria"], "verdicts": ST["verdicts"],
            "outcome": ST["outcome"], "scored_log2rho": list(P.SCORED_LOG2),
            "preobserved_log2rho": list(P.PREOBSERVED_LOG2), "tau1": Pj["tau1"], "tau2": Pj["tau2"], "rates": T,
            "DESCRIPTIVE_preobserved_rates": ST["DESCRIPTIVE_preobserved"],
            "DESCRIPTIVE_tightening_cutoff": P.criteria(P.split_scored(tight_T)[0], fr["s_F"], fr["s_star"],
                                                        Pj["tau1"], Pj["tau2"]) if g["pass"] else None}


def _f(v, d=3):
    if v is None:
        return "—"
    if isinstance(v, bool):
        return "yes" if v else "no"
    if isinstance(v, int):
        return f"{v:,}"
    if isinstance(v, float):
        return f"{v:.{d}f}"
    return str(v)


def _rate(l2):
    return f"2^{l2:g}"


def _crit_lines(C):
    out = []
    F = C["F"]
    out.append(f"| F | {F['verdict']} | {F['n_within']}/{F['n']} within [s_F, 1.25·s_F] (≥ 90%); no crossing "
               f"{F['n_no_crossing']}; falsifier (≤ 1.25·s*) at {F['n_falsifier']} rate(s) |")
    for k in ("C1", "C2"):
        c = C[k]
        out.append(f"| {k} | {c['verdict']} | {c['n_within']}/{c['n']} within τ = {c['tau']} × delay_fc (≥ 80%); "
                   f"no forecast {c['n_no_forecast']}, undefined {c['n_err_undefined']} |")
    c = C["C3"]
    out.append(f"| C3 | {c['verdict']} | Spearman(ρ, r_obs/r_fc) = {_f(c['spearman'])} (≥ 0.8) over {c['n']} rates; "
               f"ratio range {_f(c['ratio_min'])}–{_f(c['ratio_max'])} (all > 1: {_f(c['all_ratios_gt_1'])}) |")
    c = C["C4"]
    out.append(f"| C4 | {c['verdict']} | mean D = {_f(c['mean_D'], 1)} steps, 95% CI [{_f(c['ci95'][0], 1)}, "
               f"{_f(c['ci95'][1], 1)}] over {c['n']} rates (upper end < 0); no forecast {c['n_no_forecast']} |")
    c = C["E"]
    out.append(f"| E | {c['verdict']} | slope {_f(c['slope'])}, 95% CI [{_f(c['ci95'][0])}, {_f(c['ci95'][1])}] "
               f"over {c['n']} rates (inside [0.55, 0.80]) |")
    return out


def render_md(S):
    L = ["# Phase 2A results: slow tracking on the simplicity-bias benchmark", "",
         "Generated by `python -m src.phase2a_report` from `results/phase2a/scores.json` (registered `src/phase2a.py` "
         "`score`). Registration: `results/phase2a_registration.md` (commit 569b836; OpenTimestamps proof 45fcaed).", ""]
    g = S["gate"]
    L += [f"**Outcome (over the 22 scored rates): {S['outcome']}**", "",
          f"- **Gate:** {g['n_M']} of {g['n_seeds']} seeds on M (≥ {g['min_M']}): {'PASS' if g['pass'] else 'FAIL'}. "
          f"Landing counts: " + ", ".join(f"{k} {v}" for k, v in g["counts"].items()) + ".",
          f"- **τ₁ = {S['tau1']}, τ₂ = {S['tau2']}** (pilot).", ""]
    if not g["pass"]:
        return "\n".join(L) + "\n"
    v = S["validity"]
    L += ["## Verdicts (22 scored rates)", "", "| criterion | verdict | statistic |", "|---|---|---|"]
    L += _crit_lines(S["criteria"])
    L += ["", "## Validity (22 scored rates)", "",
          f"- Follow check at 0.8·s_F in M's basin: {v['follow_frac']:.3f} of rates (≥ 0.9): {_f(v['follow_ok'])}.",
          f"- t_c strictly before the crossing: {v['cutoff_before_frac']:.3f} of rates (≥ 0.9): "
          f"{_f(v['cutoff_before_ok'])} ({v['n_cutoff_not_before']} not before).",
          f"- Idle unit exactly 0 at every rate: {_f(v['idle_zero_all'])}; active signs fixed at every rate: "
          f"{_f(v['signs_fixed_all'])}.",
          f"- **Validity: {'OK' if v['ok'] else 'FAILED'}.**", ""]
    D = S["DESCRIPTIVE_preobserved_rates"]
    L += ["## DESCRIPTIVE: the 5 pre-observed rates (2⁻¹³ … 2⁻¹⁷; run, never in a verdict)", "",
          "| criterion | verdict (descriptive) | statistic |", "|---|---|---|"]
    L += _crit_lines(D["criteria"])
    L += ["", f"Validity over these 5: {'OK' if D['validity']['ok'] else 'FAILED'}.", ""]
    T = S["DESCRIPTIVE_tightening_cutoff"]
    L += ["## DESCRIPTIVE: the tightening cutoff (1 − f = 0.05·(ρ/2⁻¹⁵)^{2/3}; 22 scored rates)", "",
          "| criterion | verdict (descriptive) | statistic |", "|---|---|---|"]
    L += _crit_lines(T)
    L += ["", "## Per rate", "",
          "Pre-observed rates are marked ‡. Horizon = t_obs − t_c, in steps and in delays (÷ delay_obs). "
          "Errors are relative to delay_fc.", "",
          "| ρ | seed | t_c | t̂_F | t_fc | t_F | t_obs | s_obs/s_F | r_obs/r_fc | C1 err | C2 err | horizon steps | "
          "horizon delays | f(ρ) | C1 err at f(ρ) |",
          "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    pre = set(S["preobserved_log2rho"])
    s_F = json.loads((OUT / "frozen.json").read_text())["s_F"]
    for r in S["rates"]:
        t_obs, t_F = r.get("t_obs"), r.get("t_F")
        e1 = e2 = ratio = None
        if r.get("has_fc") and t_obs is not None and r.get("delay_fc"):
            e1 = abs(r["t_fc"] - t_obs) / r["delay_fc"]
            if t_F is not None:
                e2 = abs(r["delay_fc"] - (t_obs - t_F)) / r["delay_fc"]
        if r.get("s_obs") is not None and r.get("r_fc"):
            ratio = (r["s_obs"] / s_F - 1) / r["r_fc"]
        tg = r.get("tight") or {}
        e1t = (abs(tg["t_fc"] - t_obs) / tg["delay_fc"]) if (tg.get("t_fc") is not None and t_obs is not None
                                                            and tg.get("delay_fc")) else None
        h = r.get("horizon") or {}
        L.append("| " + " | ".join([_rate(r["log2rho"]) + (" ‡" if r["log2rho"] in pre else ""), str(r.get("seed")),
                                    _f(r["t_c"]), _f(r.get("t_F_fc")), _f(r.get("t_fc")), _f(t_F), _f(t_obs),
                                    _f(r["s_obs"] / s_F, 4) if r.get("s_obs") is not None else "—", _f(ratio),
                                    _f(e1), _f(e2), _f(h.get("steps")), _f(h.get("delays"), 2), _f(tg.get("f"), 4),
                                    _f(e1t)]) + " |")
    return "\n".join(L) + "\n"


def main():
    S = json.loads((OUT / "scores.json").read_text())
    RESULTS_MD.write_text(render_md(S))
    print(RESULTS_MD.read_text())


if __name__ == "__main__":
    main()
